lite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "tournament/",
        include(("tournament.urls", "tournament"), namespace="tournament"),
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tournament/urls.py
from django.urls import path

from . import views

app_name = 'tournament'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('bots/<int:bot_id>/', views.bot_view, name='bot'),
    path('matches/', views.MatchesView.as_view(), name='matches'),
    path('matches/<int:pk>/', views.MatchView.as_view(), name='match'),
]

tournament/models.py
from django.db import models


class Bot(models.Model):
    name = models.CharField(max_length=255, unique=True)
    docker_image = models.CharField(max_length=255)
    mu = models.FloatField(default=25.0)
    sigma = models.FloatField(default=25.0 / 3)
    enabled = models.BooleanField(default=True)
    use_gpu = models.BooleanField(default=False)

    def score(self):
        return self.mu - (self.sigma * 3)

    def __str__(self):
        return self.name


class Match(models.Model):
    date = models.DateTimeField()
    replay = models.FileField(upload_to="hlt/")
    seed = models.CharField(max_length=255)
    width = models.IntegerField()
    height = models.IntegerField()

    def __str__(self):
        return self.replay.name

    class Meta:
        verbose_name_plural = "matches"


class MatchResult(models.Model):
    bot = models.ForeignKey(Bot, related_name="matches", on_delete=models.CASCADE)
    rank = models.IntegerField()
    match = models.ForeignKey(Match, related_name="results", on_delete=models.CASCADE)
    mu = models.FloatField()
    sigma = models.FloatField()
    last_frame_alive = models.IntegerField()
    error_log = models.FileField(upload_to="error_logs", blank=True, null=True)

    def __str__(self):
        return "{0} - {1}: {2}".format(self.match, self.bot.name, self.rank)

tournament/views.py
from django.conf import settings
from django.shortcuts import render
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F

from .models import Bot, Match


class IndexView(generic.ListView):
    template_name = 'tournament/index.html'

    def get_queryset(self):
        return Bot.objects.order_by(F('mu')-(F('sigma') * 3)).reverse()


class MatchesView(generic.ListView):
    template_name = 'tournament/matches.html'
    paginate_by = settings.PAGE_SIZE

    def get_queryset(self):
        return Match.objects.order_by('-date')


def bot_view(request, bot_id):
    bot = Bot.objects.get(id=bot_id)
    paginator = Paginator(bot.matches.order_by('-match__date').all(), settings.PAGE_SIZE)

    page = request.GET.get('page')
    try:
        match_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        match_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        match_list = paginator.page(paginator.num_pages)

    return render(request, 'tournament/bot.html', {
        'bot': bot,
        'match_list': match_list,
    })


class MatchView(generic.DetailView):
    model = Match
    template_name = 'tournament/match.html'

tournament/templates/tournament/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "tournament/lib/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "tournament/style/general.css" %}" rel="stylesheet">
    {% block styles %}{% endblock %}

    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'tournament:index' %}">Halite</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'tournament:matches' %}">Matches</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.2/lodash.min.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

tournament/templates/tournament/bot.html
{% extends "tournament/base.html" %}
{% load tournament_extras %}

{% block title %}{{ bot.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>{{ bot.name }} - mu: {{ bot.mu|floatformat:3 }}, sigma: {{ bot.sigma|floatformat:3 }}</p>
                {% if match_list %}
                    <table class="table">
                        <tr>
                            <th>Time</th>
                            <th>Opponents</th>
                            <th>Result</th>
                            <th>Dimensions</th>
                            <th>mu</th>
                            <th>sigma</th>
                            <th>View</th>
                            <th>Errors</th>
                        </tr>
                        {% for match_result in match_list %}
                            <tr>
                                <td>{{ match_result.match.date|date:"m/d/Y" }} {{ match_result.match.date|time:"h:i:s A" }}</td>
                                <td>{% order_bots_by_results match_result.match bot %}</td>
                                <td>{{ match_result.rank }} of {{ match_result.match.results.all|length }}</td>
                                <td>{{ match_result.match.width }}x{{ match_result.match.height }}</td>
                                <td>{{ match_result.mu|floatformat:3 }}</td>
                                <td>{{ match_result.sigma|floatformat:3 }}</td>
                                <td>
                                    <a href="{%  url 'tournament:match' match_result.match.id %}">
                                        <span class="glyphicon glyphicon-film"></span>
                                    </a>
                                </td>
                                <td>
                                    {% if match_result.error_log %}
                                        <a href="{{ match_result.error_log.url }}">
                                            <span class="glyphicon glyphicon-exclamation-sign"></span>
                                        </a>
                                    {% else %}
                                        &mdash;
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <h2>No match results are available.</h2>
                {% endif %}
            </div>
        </div>
        {% page_links match_list %}
    </div>
{% endblock %}

tournament/templates/tournament/extras/bots_in_match.html
{% for r in results %}
    <a href="{% url 'tournament:bot' r.bot.id %}">
        {% if bot and bot.id == r.bot.id %}<u>{% endif %}{{ r.bot.name }}{% if bot and bot.id == r.bot.id %}</u>{% endif %}
        ({{ r.last_frame_alive }})
    </a>
    {% if not forloop.last %},{% endif %}
{% endfor %}

tournament/templates/tournament/extras/page_links.html
{% load tournament_extras %}

<div class="row">
    <div class="col-md-12 text-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li{% if not page.has_previous %} class="disabled"{% endif %}>
                    <a href="{% if page.has_previous %}?page={{ page.previous_page_number }}{% else %}#{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% nearby_pages page %}
                <li{% if not page.has_next %} class="disabled"{% endif %}>
                    <a href="{% if page.has_next %}?page={{ page.next_page_number }}{% else %}#{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

tournament/templates/tournament/extras/page_numbers.html
{% for page_number in page_numbers %}
    <li{% if page_number == page.number %} class="active"{% endif %}>
        <a href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
{% endfor %}

tournament/templates/tournament/index.html
{% extends "tournament/base.html" %}

{% block title %}Halite Private Tournament{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if bot_list %}
                <table class="table">
                    <tr>
                        <th>Bot</th>
                        <th>Mu</th>
                        <th>Sigma</th>
                        <th>Score</th>
                        <th>Games</th>
                        <th>Enabled</th>
                    </tr>
                    {% for bot in bot_list %}
                        <tr>
                            <td><a href="{%  url 'tournament:bot' bot.id %}">{{ bot.name }}</a></td>
                            <td>{{ bot.mu|floatformat:3 }}</td>
                            <td>{{ bot.sigma|floatformat:3 }}</td>
                            <td>{{ bot.score|floatformat:3 }}</td>
                            <td>{{ bot.matches.count }}</td>
                            <td>{% if bot.enabled %}Yes{% else %}No{% endif %}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <h2>No bots are available.</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}

tournament/templates/tournament/match.html
{% extends "tournament/base.html" %}
{% load tournament_extras static %}

{% block title %}{{ match.seed }}{% endblock %}

{% block content %}
<div id="container" class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <tr>
                    <th>Time</th>
                    <th>Opponents</th>
                    <th>Dimensions</th>
                    <th>Seed</th>
                </tr>
                <tr>
                    <td>{{ match.date|date:"m/d/Y" }} {{ match.date|time:"h:i:s A" }}</td>
                    <td>{% order_bots_by_results match %}</td>
                    <td>{{ match.width }}x{{ match.height }}</td>
                    <td>{{ match.seed }}</td>
                </tr>
            </table>
            <div id="pageContent" class="pageContent text-center"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block styles %}
<style>
    .glyphicon-refresh-animate {
        -animation: spin .7s infinite linear;
        -webkit-animation: spin2 .7s infinite linear;
    }
    @-webkit-keyframes spin2 {
        from { -webkit-transform: rotate(0deg);}
        to { -webkit-transform: rotate(360deg);}
    }
    @keyframes spin {
        from { transform: scale(1) rotate(0deg);}
        to { transform: scale(1) rotate(360deg);}
    }
</style>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/seedrandom/2.4.0/seedrandom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.2.2/pixi.min.js"></script>
<script src="{%  static "tournament/lib/xss.js" %}"></script>
<script src="{%  static "tournament/script/parsereplay.js" %}"></script>
<script src="{%  static "tournament/script/visualizer.js" %}"></script>
<script type="module">
    import initBrotli, { decompress as brotliDecompress } from "https://unpkg.com/brotli-wasm@3.0.1/pkg.web/brotli_wasm.js";
    await initBrotli();
    async function textFromAnyURL(url) {
        $("#pageContent").html("<h1><span class=\"glyphicon glyphicon-refresh glyphicon-refresh-animate\"></span> Loading replay...</h1>");

        try {
            const resp = await fetch(url);

            if (!resp.ok) {
                $("#pageContent").html(`<h1>Gamefile not found</h1><p>The gamefile at "${url}" could not be found.</p>`);
                return;
            }

            $("#pageContent").html("<h1><span class=\"glyphicon glyphicon-refresh glyphicon-refresh-animate\"></span> Preparing replay...</h1>");

            const uint8 = new Uint8Array(await resp.arrayBuffer());
            const brotliDecoded = brotliDecompress(uint8);
            const text = new TextDecoder().decode(brotliDecoded);
            showGame(textToGame(text, url), $("#pageContent"), null, null, true, false, true);

        } catch (err) {
            console.error(err);
            $("#pageContent").html(`<h1>Error loading gamefile</h1><p>${err}</p>`);
        }
    }

    // usage
    textFromAnyURL("{{ match.replay.url }}");
</script>
{% endblock %}

tournament/templates/tournament/matches.html
{% extends "tournament/base.html" %}
{% load tournament_extras %}

{% block title %}Halite Private Tournament - Matches{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if match_list %}
                    <table class="table">
                        <tr>
                            <th>Time</th>
                            <th>Opponents</th>
                            <th>Dimensions</th>
                            <th>View</th>
                        </tr>
                        {% for match in match_list %}
                            <tr>
                                <td>{{ match.date|date:"m/d/Y" }} {{ match.date|time:"h:i:s A" }}</td>
                                <td>{% order_bots_by_results match %}</td>
                                <td>{{ match.width }}x{{ match.height }}</td>
                                <td>
                                    <a href="{%  url 'tournament:match' match.id %}">
                                        <span class="glyphicon glyphicon-film"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <h2>No matches are available.</h2>
                {% endif %}
            </div>
        </div>
        {% if is_paginated %}
            {% page_links page_obj %}
        {% endif %}
    </div>
{% endblock %}